@startuml MyLatLng Diagram
class MyLatLng {
  ..<<readonly>>..

  - longitude : number
  - latitude : number
  - leafletLatLng : LatLng
  ....
  ==constructor==

  + constructor(
    latitude : number,
    longitude : number,
    leafletLatLng ?: LatLng
    )
  ==methods==

  + getLeafletLatLng() : LatLng
  + getLongitude() : number
  + getLatitude() : number
}

/'
' if you decomment this part it will no longer appear within the package
' leaflet, this part has already been moved to the main file, it's here
' just to remember it
'/
' MyLatLng --> LatLng
@enduml
