@startuml MyLatLng Diagram
class MyLatLng {
  ..<<readonly>>..

  - longitude : number
  - latitude : number
  - leafletLatLng : LatLng
  ....
  ==constructor==

  + constructor(
    latitude : number,
    longitude : number,
    leafletLatLng ?: LatLng
    )
  ==methods==

  + getLeafletLatLng() : LatLng
  + getLongitude() : number
  + getLatitude() : number
}

MyLatLng --> LatLng
@enduml
