@startuml PlaceDataBuilder Diagram
class AbsPlaceDataBuilder {
  ==methods==
  + build()
}
class PlaceDataBuilder {
  ==constructor==

  + constructor(
    private address : string,
    private city : string,
    private zipcode : string,
    private state : string,
  )
  ==methods==

  + addAddress(address : string) : PlaceDataBuilder
  + addCity(city : string) : PlaceDataBuilder
  + addZipcode(zipcode : string) : PlaceDataBuilder
  + addState(state : string) : PlaceDataBuilder
  + build() : PlaceData
}

PlaceDataBuilder ..> "<<create>>" PlaceData
@enduml
