@startuml PlaceBuilder Diagram
class AbsPlaceBuilder {
  ==methods==
  + addPlaceData(placeData : PlaceData)
  + build()
}
class PlaceBuilder {
  - id : integer
  - name : string
  - placeData : PlaceData
  == contructor ==

  + constructor(private polyline : MyLatLng[])
  == methods ==

  + addId(id : integer) : PlaceBuilder
  + addName(name : string) : PlaceBuilder
  + addPolyline(polyline : MyLatLng[]) : PlaceBuilder
  + addPlaceData(placeData : PlaceData) : PlaceBuilder
  + build() : Place
}

PlaceBuilder --> PlaceData
PlaceBuilder --> MyLatLng
PlaceBuilder ..> Place
@enduml
