@startuml PlaceDataBuilder Diagram
class PlaceDataBuilder {
  - address : string
  - city : string
  - zipcode : string
  - state : string
  ==methods==

  + addAddress(address : string) : PlaceDataBuilder
  + addCity(city : string) : PlaceDataBuilder
  + addZipcode(zipcode : string) : PlaceDataBuilder
  + addState(state : string) : PlaceDataBuilder
  + build() : PlaceData
}
@enduml
