@startuml UserData Diagram
!include ../../../style/class.pu
interface UserData <<interface>> {
  ..<<readonly>>..

  - firstName : string
  - lastName : string
  - birthDate : string
  - createdDate : string
  - lastModifiedDate : string
  ....
}
@enduml
