@startuml User Diagram
!include ../../../style/class.pu
interface User <<interface>> {
  ..<<readonly>>..

  + id ?: integer
  + userData ?: UserData
  + loginData ?: LoginData
  ....
}

User o-- UserData
User o-- LoginData
@enduml
