@startuml LdapConfigurationBuilder diagram
class LdapConfigurationBuilder {
  - username ?: string
  - password ?: string
  ==constructor==

  + constructor(private host : string)
  ==methods==

  + addHost(host : string) : LdapConfigurationBuilder
  + addUsername(username : string) : LdapConfigurationBuilder
  + addPassword(password : string) : LdapConfigurationBuilder
  + build() : LdapConfiguration
}

LdapConfigurationBuilder ..> "<<create>>" LdapConfiguration
@enduml
