@startuml FormEmailComponent diagram
class FormEmailComponent {
  + emailForm : FormGroup
  ==methods==

  + ngOnInit() : void
  + onTouched()
  + writeValue(val: MailType) : void
  + registerOnChange(fn: () => void) : void
  + registerOnTouched(fn: () => void) : void
}

interface MailType {
  + email : string
}

FormEmailComponent .. MailType
@enduml
