@startuml FormPasswordComponent diagram
class FormPasswordComponent {
  + pwdForm : FormGroup
  + hide : boolean
  ==methods==

  + ngOnInit()
  + onTouched()
  + writeValue(val: PwdType)
  + registerOnChange(fn: () => void)
  + registerOnTouched(fn: () => void)
}

interface PwdType {
  + pwd : string
}
@enduml
