@startuml FormPasswordComponent diagram
class FormPasswordComponent {
  + pwdForm : FormGroup
  + hide : boolean
  ==methods==

  + ngOnInit() : void
  + onTouched()
  + writeValue(val: PwdType) : void
  + registerOnChange(fn: () => void) : void
  + registerOnTouched(fn: () => void) : void
}

interface PwdType {
  + pwd : string
}
@enduml
