@startuml MapComponent diagram
class MapComponent {
  ..<<readonly>>..
  - placeService : PlaceService,
  - organizationService : OrganizationService,
  ....
  + arrayCoord : LatLng[]
  + arrayRoad : string[]
  + arrayCity : string[]
  + arrayPostcode : string[]
  + arrayCountry : string[]
  + arrayName : string[]
  + organization : Organization
  + organizationBuilder : AbsOrganizationBuilder
  + options : object
  + drawOptions : object
  + polygonLayers : Polygon[]
  + bounds: LatLngBounds[]
  ==constructor==

  + constructor(
    private <<readonly>> placeService : PlaceService,
    private <<readonly>> organizationService : OrganizationService,
  )
  ==methods==

  + ngOnInit() : void
  + onDrawCreated(e : {layer : Polygon}) : void
  + getOrganizationById(id : integer) : void
  + getRandomColor() : string
  + getCentroid(latlngs : LatLng[]) : LatLng
}
@enduml
