@startuml Class Diagram
class UserData{
  __ private data __
  - firstName : string
  - lastName : string
  - birthDate : date
  ==
  + UserData(firstName : string, lastName : string, birthDate : date)
  + getfirstName()
  + getlastName()
  + getBirthDate()
  + setfirstName(newFirstName : string)
  + setlastName(NewLastName : string)
  + setBirthDate(NewBirthDate : date)
}
@enduml
