@startuml UserBuilder Diagram

class AbsUserBuilder {
  + addUserData()
  + addLoginData()
  + build()
}
class UserBuilder {
  - id : integer
  - userData ?: UserData
  - loginData ?: LoginData
  == constructor ==

  + constructor(id: integer)
  == methods ==

  + addId(id : integer) : UserBuilder
  + addUserData(userData : UserData) : UserBuilder
  + addLoginData(loginData: Logindata) : UserBuilder
  + build() : User
}
UserBuilder --|> AbsUserBuilder
UserBuilder --> UserData
UserBuilder ..> "<<create>>" User
@enduml
