@startuml UserDataBuilder Diagram
class UserDataBuilder {
  - firstName : string
  - lastName : string
  - birthDate : string
  - createdDate : string
  - lastModifiedDate : string
  ==methods==

  + addFirstName(firstName : string) : UserDataBuilder
  + addLastName(lastName : string) : UserDataBuilder
  + addBirthDate(birthDate : string) : UserDataBuilder
  + addCreatedDate(createdDate : string) : UserDataBuilder
  + addLastModifiedDate(lastModifiedDate : string) : UserDataBuilder
  + build() : UserData
}
@enduml
