@startuml UserBuilder Diagram
class UserBuilder {
  - id : integer
  - userData : UserData
  == constructor ==

  + constructor(private email : string, private password : string)
  == methods ==

  + addId(id : integer) : UserBuilder
  + addEmail(email : string) : UserBuilder
  + addPassword(password : string) : UserBuilder
  + addUserData(userData : UserData) : UserBuilder
  + build() : User
}

UserBuilder -- UserData
UserBuilder .. User
@enduml
