@startuml Class Diagram
class User{
  __ private data __
  - id : number
  - email : string
  - password : string
  - data : UserData
  ==
  + User(id : number, email : string, password : string, data : UserData)
  + User(email : string, password : string)
  + getId()
  + getEmail()
  + getPassword()
  + getData()
  + setPassword(newPassword : string)
}
@enduml
