@startuml Place Diagram
interface Place <<interface>> {
  ..<<readonly>>..

  + id ?: number
  + name ?: string
  + polyline : MyLatLng[]
  + placeData ?: PlaceData
  ....
  == methods ==

  + getLatLng(polyline : MyLatLng[]) : LatLng[]
}

Place --> MyLatLng
Place -- PlaceData

/'
' if you decomment this part it will no longer appear within the package
' leaflet, this part has already been moved to the main file, it's here
' just to remember it
'/
' Place ..> LatLng
@enduml
