@startuml Place Diagram
interface Place <<interface>> {
  ..<<readonly>>..

  + id ?: number
  + name ?: string
  + polyline : MyLatLng[]
  + placeData ?: PlaceData
  ....
  == methods ==

  + getLatLng(polyline : MyLatLng[]) : LatLng[]
}

Place --> MyLatLng
Place -- PlaceData
Place ..> LatLng
@enduml
