@startuml EditOrganizationComponent diagram
class EditOrganizationComponent {
  - mapDataChild ?
  - organization ?: Organization
  - organizationBuilder ?: OrganizationBuilder
  - organizationUsers : User[]
  - formGroup : FormGroup
  == constructor ==

  + constructor(
    private <<readonly>> formBuilder : FormBuilder,
    private <<readonly>> organizationService : OrganizationService,
    private <<readonly>> administratorService : AdministratorService,
    private <<readonly>> connectedUserService : ConnectedUserService
    )
  == methods ==
  + ngOnInit(): void
  + get formArray() : AbstractControll | null
  + getOrganizationById(id: integer) : void
  + submitOrganizationForm() : void
  + addAdmin() : void
  + deleteAdmin(administratorId : integer) : void
  + getOrgAdministrators(organizationId : integer): void
  + getOrgUsers(organizationId : integer) : void
  + checkifEmailIsUser(email : string, userList : User[]) : integer
}
@enduml
