@startuml EditOrganizationComponent
class EditOrganizationComponent {
  - mapDataChild?
  - organization?: Organization
  - organizationBuilder?: OrganizationBuilder
  - organizationUsers: User[]
  - formGroup: FormGroup
  == constructor ==

  + constructor(
    private <<readonly>> formBuilder : FormBuilder,
    private <<readonly>> organizationService : OrganizationService,
    private <<readonly>> administratorService : AdministratorService,
    private <<readonly>> connectedUserService : ConnectedUserService
    )
  == methods ==
  + ngOnInit(): void
  + get formArray(): AbstractControll | null
  + getOrganizationById(id: number): void
  + submitOrganizationForm(): void
  + addAdmin(): void
  + deleteAdmin(administratorId: number): void
  + getOrgAdministrators(organizationId: number): void
  + getOrgUsers(organizationId: number): void
  + checkifEmailIsUser(email: string, userList: User[]): number
}
@enduml
