@startuml HomeComponent diagram
class HomeComponent {
  ..<<readonly>>..
  - loginService : LoginService,
  - router : Router,
  - titleService : Title,
  ....
  + toggle : boolean
  + nestedForm : FormGroup
  + loginDataBuilder : AbsLoginDataBuilder
  ==constructor==

  + constructor(
    private <<readonly>> loginService : LoginService,
    private <<readonly>> router : Router,
    private <<readonly>> titleService : Title,
  )
  ==methods==

  + ngOnInit() : void
  + login(email : string, password : string) : void
  + validateInput(
    email : string,
    password : string
    ) : boolean
  + translate(i : integer) : void
}
@enduml
