@startuml HomeComponent diagram
class HomeComponent {
  + toggle : boolean
  + nestedForm : FormGroup
  ==constructor==

  + constructor(
    private <<readonly>> loginService : LoginService,
    private <<readonly>> router : Router,
    private <<readonly>> titleService : Title,
  )
  ==methods==

  + ngOnInit() : void
  + login(email : string, password : string) : void
  + validateInput(
    email : string,
    password : string
    ) : boolean
  + translate(i : number) : void
}
@enduml
