@startuml OrganizationsComponent diagram
class OrganizationsComponent {
  ..<<readonly>>..
  - organizationService: OrganizationService
  ....
  - displayedColumns : string[]
  - dataSource : MatTableDataSource
  - paginator : MatPaginator
  - sort : MatSort
  - organizationsRoles : object
  ==constructor==

  + constructor(
    private <<readonly>> organizationService: OrganizationService
    )
  ==methods==

  + ngOnInit() : void
  + applyFilter(event : Event) : void
  + getAdminOrganizations() : void
}
@enduml
