@startuml OrganizationComponent diagram
class OrganizationComponent {
  - organization?: Organization
  - organizationBuilder?: OrganizationBuilder
  == constructor ==

  + constructor(
    private <<readonly>> organizationService: OrganizationService
    )
  == methods ==

  + ngOnInit() : void
  + getOrganizationById(id: integer): void
}
@enduml
