@startuml OrganizationComponent

class OrganizationComponent {
  - organization?: Organization
  - organizationBuilder?: OrganizationBuilder
  == constructor ==

  constructor(private readonly organizationService: OrganizationService)
  == methods ==

  + ngOnInit() : void
  + getOrganizationById(id: number): void
}
@enduml
