@startuml ProfileComponent diagram
class ProfileComponent {
  - userBuilder : UserBuilder
  + fetched : boolean
  + user : User
  ==constructor==

  + constructor(private <<readonly>> userService : UserService)
  ==methods==

  + ngOnInit() : void
  + getUser(id: integer) : void
}
@enduml
