@startuml ConnectedUserService

class ConnectedUserService {
  == constructor ==

  + constructor(private readonly httpClientService: HttpClientService)
  == methods ==

  + getUserConnectedToOrg(organizationId: number): Observable<User[]>
}
@enduml
