@startuml LoginService
class LoginService {
  == constructor ==

  + constructor(httpClient : HttpClientService)
  == methods ==

  + login(user : User): Observable<User>
  + checkPermissionOnOrg(role: AdminType, organizationId: number): boolean
  + logout(): void
  + isLoggedIn(): boolean
}
@enduml
