@startuml OrganizationService
class OrganizationService {
  == constructor ==

 + constructor(
   private <<readonly>> httpClientService: HttpClientService,
   private <<readonly>> loginService: LoginService
   )
 == methods ==
 + addOrganization(
   organization: Organization
   ) : Observable<Organization>
 + getOrganization(
   organizationId : integer
   ) : Observable<Organization>
    + getAdminOrganizations() : Observable<Organization>
 + editOrganization(
   organization : Organization
   ) : Observable<Organization>
}
@enduml
