@startuml OrganizationService
class OrganizationService {
  == constructor ==

 + constructor(private readonly httpClientService: HttpClientService)
 == methods ==
 + addOrganization(organization: Organization): Observable<Organization>
 + getOrganization( organizationId : number): Observable<Organization>
 + editOrganization( organization : Organization): Observable<Organization>
}
@enduml
