@startuml PlaceService

interface Geocoding {
  + display_name : string
  + address : AddressType
}

interface AddressType {
  + city : string
  + country : string
  + postcode : string
  + road : string
}

class PlaceService {
  == constructor ==

  + constructor(
    private <<readonly>> httpClient : HttpClient
    )
  == methods ==

  + reverseGeocoding(
    lat : number,
    lng : number
    ) : Observable<Geocoding>
}

Geocoding *-- AddressType
PlaceService .. Geocoding
@enduml
