@startuml UserService
class UserService {
  ..<<readonly>>..
  - httpClientService: HttpClientService
  ....
  == constructor ==

  + constructor(
    private <<readonly>> httpClientService : HttpClientService
    )
  == methods ==

  + getUserById(userId: integer): Observable<User>
}
@enduml
