@startuml UserService
class UserService {
  == constructor ==

  + constructor(private readonly httpClientService: HttpClientService)
  == methods ==

  + getUserById(userId: number): Observable<User>
}
@enduml
