@startuml ConnectedUserService

class ConnectedUserService {
  ..<<readonly>>..
  - httpClientService: HttpClientService
  ....
  == constructor ==

  + constructor(
    private <<readonly>> httpClientService: HttpClientService
    )
  == methods ==

  + getUserConnectedToOrg(
    organizationId: integer
    ): Observable<User[]>
}
@enduml
