@startuml LoginService
class LoginService {
  ..<<readonly>>..
  - httpClientService: HttpClientService
  ....
  == constructor ==

  + constructor(
    private <<readonly>> httpClientService : HttpClientService,
    private <<readonly>> router: Router
    )
  == methods ==

  + login(user : User) : Observable<User>
  + checkPermissionOnOrg(
    role : AdminType,
    organizationId : integer
    ) : boolean
  + logout() : void
  + isLoggedIn() : boolean
  + getUserId(): string
  + getAdminOrganizations():
  {organizationId: integer, role: AdminType}
}
@enduml
