@startuml Login Builder Diagram
!include ../../../style/class.pu
class AbsLoginDataBuilder {
  + build()
}
class LoginDataBuilder {
  - id : integer
  - userData : UserData
  - loginData : LoginData
  == constructor ==

  + constructor(id: integer)
  == methods ==
  + addEmail(email : string) : LoginDataBuilder
  + addPassword(password : string) : LoginDataBuilder
  + build() : User
}

LoginDataBuilder ..> "<<create>>" LoginData
LoginDataBuilder --|>  AbsLoginDataBuilder
@enduml
