@startuml Organization Diagram
interface Organization <<interface>> {
  ..<<readonly>>..

  + id : integer
  + name : string
  + description : string
  + ldapConfiguration : LdapConfiguration
  + isPrivate : boolean
  + createdDate : string
  + lastModifiedDate : string
  ....
  + places  : Place[]
}

Organization --> LdapConfiguration
Organization --> Place
@enduml
