@startuml CreateOrganizationComponent diagram
class CreateOrganizationComponent {
  ..<<readonly>>..
  - formBuilder : FormBuilder
  - organizationService : OrganizationService
  ....
  - router : Router
  - toggle : boolean
  - mapDataChild
  - organizationBuilder : OrganizationBuilder
  - placeBuilder : AbsPlaceBuilder
  - formGroup : FormGroup
  ==constructor==

  + constructor(
    private <<readonly>> formBuilder : FormBuilder
    private <<readonly>> organizationService : OrganizationService
    private <<readonly>> router : Router
  )
  ==methods==

  + ngOnInit() : void
  + get formArray() : AbstractControl | null
  + submitOrganizationForm() : void
  + showLdapConfiguration() : void
}
@enduml
