@startuml OrganizationBuilder Diagram
class OrganizationBuilder {
  - id ?: integer
  - description ?: string
  - ldapConfiguration ?: LdapConfiguration
  - places ?: Place[]
  - createdDate ?: string
  - lastModifiedDate ?: string
  == constructor ==

  + constructor(private name : string, private isPrivate : boolean)
  == methods ==

  + addId(id : integer) : OrganizationBuilder
  + addName(name : string) : OrganizationBuilder
  + addDescription(description : string) : OrganizationBuilder
  + addLdapConfiguration(
    ldapConfiguration : LdapConfiguration
    ) : OrganizationBuilder
  + addPlaces(places : Place[]) : OrganizationBuilder
  + addIsPrivate(isPrivate : boolean) : OrganizationBuilder
  + addCreatedDate(createdDate : string) : OrganizationBuilder
  + addLastModifiedDate(
    lastModifiedDate : string
    ) : OrganizationBuilder
  + build() : Organization
}

OrganizationBuilder -- LdapConfiguration
OrganizationBuilder -- Place
OrganizationBuilder .. Organization
@enduml
