@startuml UserData Diagram
interface UserData <<interface>> {
  ..<<readonly>>..

  - firstName ?: string
  - lastName ?: string
  - birthDate ?: string
  - createdDate ?: string
  - lastModifiedDate ?: string
  ....
}
@enduml
