@startuml Class Diagram

' START include interfaces
' -------------------------------------------------- User
!include interfaces/User/User.pu
!include interfaces/User/UserData.pu

' -------------------------------------------------- Place
!include interfaces/Place/Place.pu
!include interfaces/Place/PlaceData.pu

' -------------------------------------------------- Organization
!include interfaces/Organization/Organization.pu
' END include interfaces

'---------------------------------------------------

' START include classes
' -------------------------------------------------- UserBuilder
!include classes/User/UserBuilder.pu

' -------------------------------------------------- PlaceBuilder
!include classes/Place/PlaceBuilder.pu

' -------------------------------------------------- OrganizationBuilder
!include classes/Organization/OrganizationBuilder.pu
' END include classes

'---------------------------------------------------

' START include services

!include services/auth-http-interceptorservice.pu
!include services/loginservice.pu
!include services/organizationservice.pu
!include services/userservice.pu
!include services/placeservice.pu
!include services/http-clientservice.pu
!include services/connected-userservice.pu

' END include services

'---------------------------------------------------

' START include components

!include view/components/MapComponent.pu
!include view/components/ButtonConfirmComponent.pu
!include view/components/FormEmailComponent.pu
!include view/components/FormPasswordComponent.pu

!include view/routes/editorganizationcomponent.pu
!include view/routes/HomeComponent.pu
!include view/routes/NotFoundComponent.pu
!include view/routes/organizationcomponent.pu
!include view/routes/ProfileComponent.pu
!include view/routes/OrganizationsComponent.pu

' END include components

class environment{
  + apiUrl : string
}

LoginComponent o-- AuthenticationService
AuthenticationService ..> User
LoginComponent --> User
Organization *-- UserRole
Organization *-- Place
UserRole --> Role
Place *-- MyLatLng
Place *-- PlaceData
User *-- UserData
HomePageComponent o-- AuthenticationService
ProfileComponent o-- AuthenticationService
TopBarComponent o-- AuthenticationService
ShowOrganizationComponent o-- AuthenticationService
OrganizationRequestComponent o-- AuthenticationService
TopBarComponent --> User
ProfileComponent --> User
ShowOrganizationComponent --> Organization
ShowOrganizationComponent ..> User
OrganizationRequestComponent ..> Organization
TopBarComponent o-- UserService
ProfileComponent o-- UserService
ShowOrganizationComponent o-- UserService
ShowOrganizationComponent o-- OrganizationService
OrganizationRequestComponent o-- OrganizationService
UserService ..> User
OrganizationService ..> Organization
@enduml
