@startuml Class Diagram

' START include interfaces
' -------------------------------------------------- User
!include interfaces/User/User.pu
!include interfaces/User/UserData.pu
!include interfaces/User/UserRole.pu

' -------------------------------------------------- Place
!include interfaces/Place/Place.pu
!include interfaces/Place/MyLatLng.pu
!include interfaces/Place/PlaceData.pu

' -------------------------------------------------- Organization
!include interfaces/Organization/Organization.pu
' END include interfaces

'---------------------------------------------------

' START include classes
' -------------------------------------------------- UserBuilder
!include classes/UserBuilder/UserBuilder.pu

' -------------------------------------------------- PlaceBuilder
!include classes/PlaceBuilder/PlaceBuilder.pu

' -------------------------------------------------- OrganizationBuilder
!include classes/OrganizationBuilder/OrganizationBuilder.pu
' END include classes

'---------------------------------------------------

' START include services

!include services/auth-http-interceptorservice.pu
!include services/loginservice.pu
!include services/organizationservice.pu
!include services/userservice.pu
!include services/placeservice.pu
!include services/http-clientservice.pu
!include services/connected-userservice.pu

' END include services

'---------------------------------------------------


class LoginComponent {
  __ private data __
  - User : user
  ==
  + constructor(auth : AuthenticationService)
  + login()
  + loginError()
}

class environment{
  + apiUrl : string
}


class HomePageComponent {
 + constructor(auth : AuthenticationService)
}

class TopBarComponent {
 __ private data __
 - User : user
 ==
 + constructor(auth : AuthenticationService, userService : UserService)
 + getUser()
 + getDate()
 + getTime()
}

class ProfileComponent {
  __ private data __
  - User : user
  ==
  + constructor(auth : AuthenticationService, userService : UserService)
  + getUser()
}

class ShowOrganizationComponent {
  __ private data __
  - organizations : Organization[]
  ==
  + constructor(auth : AuthenticationService, userService : UserService, organizationService : OrganizationService)
  + getOrganizations( userId : number)
}

class OrganizationRequestComponent {
  + constructor(auth : AuthenticationService, userService : UserService, organizationService : OrganizationService)
  + sendRequest( organization : Organization)
}

class MonitorOrganizationComponent
class ShowEmployeesComponent
class ShowPlacesComponent
class ManagePlacesComponent
class ManageOrganizationsComponent
class ManageUsersComponent

class OrganizationListComponent
class OrganizationListService
class OrganizationDetailsComponent
class OrganizationDetailsService
LoginComponent o-- AuthenticationService
AuthenticationService ..> User
LoginComponent --> User
Organization *-- UserRole
Organization *-- Place
UserRole --> Role
Place *-- MyLatLng
Place *-- PlaceData
User *-- UserData
HomePageComponent o-- AuthenticationService
ProfileComponent o-- AuthenticationService
TopBarComponent o-- AuthenticationService
ShowOrganizationComponent o-- AuthenticationService
OrganizationRequestComponent o-- AuthenticationService
TopBarComponent --> User
ProfileComponent --> User
ShowOrganizationComponent --> Organization
ShowOrganizationComponent ..> User
OrganizationRequestComponent ..> Organization
TopBarComponent o-- UserService
ProfileComponent o-- UserService
ShowOrganizationComponent o-- UserService
ShowOrganizationComponent o-- OrganizationService
OrganizationRequestComponent o-- OrganizationService
UserService ..> User
OrganizationService ..> Organization
@enduml
