@startuml Administrator
interface Administrator <<interface>> {
  ..<<readonly>>..

  + id : integer
  + email : string
  + role : AdminType
  ....
}

enum AdminType <<enumeration>> {
  + manager = 'Manager'
  + viewer = 'Viewer'
}

Administrator --> AdminType
@enduml
