@startuml AuthGuard diagram
class AuthGuard {
  ==constructor==

  + constructor(
    private <<readonly>> loginService : LoginService,
    private <<readonly>> router : Router,
    private <<readonly>> location : Location,
    )
  ==methods==

  + canActivate(route: ActivatedRouteSnapshot) : boolean
}
@enduml
