@startuml LdapConfiguration diagram
!include ../../../style/class.pu
interface LdapConfiguration <<interface>> {
  ..<<readonly>>..

  + host : string
  + username ?: string
  + password ?: string
  ....
}
@enduml
