@startuml stylesheet

skinparam {
  ArrowColor #000
  BackgroundColor #dfdfdf
  DefaultFontName Roboto
  Linetype ortho
  NoteFontName Roboto
  ' HeaderBackgroundColor non funziona più se facciamo gli angoli arrotondati
  ' roundCorner 10

  Class {
    BackgroundColor #fff
    BorderColor #989898
    FontStyle bold
    HeaderBackgroundColor #add1b2
    StereotypeFontStyle normal
  }

  Class<<interface>> {
    HeaderBackgroundColor #b4a7e5
  }

  Class<<enumeration>> {
    HeaderBackgroundColor #eb937f
  }

  Package {
    BackgroundColor #b3b3b3
    BorderColor #989898
  }

  Note {
    BackgroundColor #b3b3b3
    BorderColor #989898
  }
}
@enduml
