@startuml MyLatLng Diagram
!include ../../../style/class.pu
class MyLatLng {
  ..<<readonly>>..

  - longitude : double
  - latitude : double
  - leafletLatLng : LatLng
  ....
  ==constructor==

  + constructor(
    latitude : double,
    longitude : double,
    leafletLatLng  : LatLng
    )
  ==methods==

  + getLeafletLatLng() : LatLng
  + getLongitude() : double
  + getLatitude() : double
}

/'
' if you decomment this part it will no longer appear within the package
' leaflet, this part has already been moved to the main file, it's here
' just to remember it
'/
' MyLatLng --> LatLng
@enduml
