@startuml AuthGuard diagram
class AuthGuard {
  ..<<readonly>>..
  - loginService : LoginService
  - router : Router
  - location : Location
  ....
  ==constructor==

  + constructor(
    private <<readonly>> loginService : LoginService,
    private <<readonly>> router : Router,
    private <<readonly>> location : Location,
    )
  ==methods==

  + canActivate(route: ActivatedRouteSnapshot) : boolean
}
@enduml
