@startuml PlaceData Diagram
!include ../../../style/class.pu
class PlaceData <<interface>> {
  ..<<readonly>>..

  + address : string
  + city : string
  + zipcode : string
  + state : string
  ....
}
@enduml
