name: Source files best practices

on:
  pull_request:
    branches:
      - master

jobs:
  check-files:
    name: No BOMs or CRLFs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for BOMs
        uses: arma-actions/bom-check@v1.0

      - name: Check for CRLF endings
        if: always()
        uses: erclu/check-crlf@v1
