name: Continuous Integration

# run jobs on any PRs and main branch changes
on:
  pull_request:
  push:
    branches:
      - master

# STEPS EXPLANATIONS

# uses: actions/cache@v1
# with:
#   path: ~/.npm
#   key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
#
# npm cache files are stored in `~/.npm` on Linux/macOS
# the given key changes ONLY when package.json changes

# - name: ...
#   run: npx ng ..
#
# we use npx to run ng, this way it should pick up the angular cli that was installed in the previous step

# TODO find a way to reduce duplication in jobs (the first steps are repeated)
# TODO add coverage job
jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Cache node modules
      #   id: cache
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run karma
        run: npm run --silent test -- --configuration=ci

  # TODO upload results to either codecov or coveralls
  run-code-coverage:
    name: Coverage
    runs-on: ubuntu-latest

    # runs only if unit-tests job succeeds
    needs: run-unit-tests

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Run karma with code coverage option
        run: npm run --silent coverage -- --configuration=ci

  run-system-tests:
    name: Run system tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Run protractor
        run: npm run --silent e2e -- --configuration=ci
