name: Conventional Commits

on:
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  commitsar:
    name: Check all commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run commitsar
        uses: docker://outillage/commitsar:0.11.1
