name: Documentation jobs

on:
  pull_request:
    branches:
      - master

jobs:
  lint-markdown:
    name: Lint markdown files
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          ignore_files: 'CHANGELOG.md'
