name: Dynamic analysis and testing

# run jobs on any PRs and main branch changes
on:
  pull_request:
    branches:
      - master
  # needs to be redone on push to master in order to update coveralls
  push:
    branches:
      - master

# STEPS EXPLANATIONS

# uses: actions/cache@v1
# with:
#   path: ~/.npm
#   key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
#
# npm cache files are stored in `~/.npm` on Linux/macOS
# the given key changes ONLY when package.json changes

# TODO find a way to reduce duplication in jobs (the first steps are repeated)
jobs:
  unit-tests:
    name: Unit tests passing and Coverage > 80%
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        id: cache-node-modules
        env:
          cache-name: node-modules-cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: cache-${{ env.cache-name }}-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run karma
        run: npm run --silent test -- --configuration=ci

      - name: Upload results to coveralls.io
        if: always()
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/stalker-web-app/lcov.info

  system-tests:
    name: System tests passing
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        id: cache-node-modules
        env:
          cache-name: node-modules-cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: cache-${{ env.cache-name }}-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Update to latest chrome
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y google-chrome-stable

      - name: Run protractor
        run: npm run --silent e2e -- --configuration=ci
