name: Project management

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

  push:
    branches-ignore:
      - master

jobs:
  assign_one_project:
    name: Assign to main project board
    runs-on: ubuntu-latest

    env:
      MY_GITHUB_TOKEN: ${{ secrets.ERCLU_ORGANIZATION_TOKEN }}

    if: github.event_name != 'push'

    steps:
      - name: Assign new issues and new PRs to the main organization project board
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/orgs/GruppOne/projects/9'
          column_name: 'To do'

  # TODO test if it works
  create-pr-on-push:
    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    steps:
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          title: 'An automatically created PR from ${{ github.ref }} to master'
          draft: true
